In [ ]:
from google.colab import files

uploaded = files.upload()

Saving Merged_Higher_Education_Dashboard_50.xlsx to Merged_Higher_Education_Dashboard_50 (1).xlsx

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_excel("/content/Merged_Higher_Education_Dashboard_50.xlsx")

df.head()

,University,Country,QS_Rank,Overall_Score_QS,Academic_Reputation,Employer_Reputation,Citations_per_Faculty,Faculty_Student_Ratio,International_Students,THE_Rank,Overall_Score,Teaching,Research,Citations,Industry_Income,International_Outlook
0,MIT,USA,1,100.0,100,99,98,97,96,1,99.5,99,98,99,95,97
1,University of Oxford,UK,2,99.2,99,98,97,96,95,2,98.8,98,97,99,94,96
2,Stanford University,USA,3,98.4,99,98,97,96,95,4,98.0,98,97,98,94,96
3,Harvard University,USA,4,97.6,98,97,96,95,94,6,97.2,97,96,98,93,95
4,University of Cambridge,UK,5,96.8,98,97,96,95,94,3,96.5,97,96,98,93,95

In [ ]:
print(df.columns.tolist())

['University', 'Country', 'QS_Rank', 'Overall_Score_QS', 'Academic_Reputation', 'Employer_Reputation', 'Citations_per_Faculty', 'Faculty_Student_Ratio', 'International_Students', 'THE_Rank', 'Overall_Score', 'Teaching', 'Research', 'Citations', 'Industry_Income', 'International_Outlook']

In [ ]:
max_rank = df["QS_Rank"].max()
min_rank = df["QS_Rank"].min()

df["Global_Ranking_Score"] = (
    (max_rank - df["QS_Rank"]) /
    (max_rank - min_rank)
) * 100

df["Global_Ranking_Score"] = df["Global_Ranking_Score"].round(2)

In [ ]:
df["Research_Impact_Score"] = (
    df["Research"] * 0.6 +
    df["Citations"] * 0.4
).round(2)

In [ ]:
df["Faculty_to_Student_Ratio"] = (
    df["Faculty_Student_Ratio"]
).round(2)

In [ ]:
df["International_Student_Percentage"] = (
    df["International_Students"]
).round(2)

In [ ]:
df["Academic_Reputation_Score"] = (
    df["Academic_Reputation"]
).round(2)

In [ ]:
df["Academic_Reputation_Score"] = (
    df["Academic_Reputation"]
).round(2)

In [ ]:
df["Research_Productivity_Index"] = (
    (df["Research"] + df["Citations"] + df["Industry_Income"]) / 3
).round(2)

In [ ]:
df[
    [
        "University",
        "Global_Ranking_Score",
        "Research_Impact_Score",
        "Faculty_to_Student_Ratio",
        "International_Student_Percentage",
        "Academic_Reputation_Score",
        "Research_Productivity_Index"
    ]
].head()

,University,Global_Ranking_Score,Research_Impact_Score,Faculty_to_Student_Ratio,International_Student_Percentage,Academic_Reputation_Score,Research_Productivity_Index
0,MIT,100.00,98.4,97,96,100,97.33
1,University of Oxford,97.96,97.8,96,95,99,96.67
2,Stanford University,95.92,97.4,96,95,99,96.33
3,Harvard University,93.88,96.8,95,94,98,95.67
4,University of Cambridge,91.84,96.8,95,94,98,95.67

In [ ]:
df.to_excel("university_final_dataset.xlsx", index=False)

print("KPI Engineering Completed Successfully!")

KPI Engineering Completed Successfully!